
DROP TABLE trip_request CASCADE CONSTRAINTS;
DROP TABLE trip CASCADE CONSTRAINTS;
DROP TABLE transport CASCADE CONSTRAINTS;
DROP TABLE driver_vehicle_type CASCADE CONSTRAINTS;
DROP TABLE driver CASCADE CONSTRAINTS;
DROP TABLE vehicle_type CASCADE CONSTRAINTS;
DROP TABLE status;


CREATE TABLE vehicle_type (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name VARCHAR2(100) NOT NULL
); 


CREATE TABLE transport (
    number_plate VARCHAR(20) PRIMARY KEY,
    vehicle_type_id NUMBER,
    start_exploitation DATE,
    end_exploitation DATE,
    FOREIGN KEY (vehicle_type_id) REFERENCES vehicle_type(id)
);


CREATE TABLE driver (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(255) NOT NULL,
    employment_start DATE
);


CREATE TABLE driver_vehicle_type (
    driver_id NUMBER,
    vehicle_type_id NUMBER,
    FOREIGN KEY (driver_id) REFERENCES driver(id),
    FOREIGN KEY (vehicle_type_id) REFERENCES vehicle_type(id)
);


CREATE TABLE status (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_name varchar2(20) NOT NULL
);




CREATE TABLE trip_request (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_name VARCHAR2(255) NOT NULL,
    distance NUMBER,
    creation_date DATE NOT NULL,
    status_id NUMBER,
    required_vehicle_type_id NUMBER,
    start_datetime TIMESTAMP,
    end_datetime TIMESTAMP,
    FOREIGN KEY (required_vehicle_type_id) REFERENCES vehicle_type(id),
    FOREIGN KEY (status_id) REFERENCES status(id)
);



CREATE TABLE trip (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_request_id NUMBER NOT NULL UNIQUE,
    transport_id VARCHAR(15),
    driver_id NUMBER,
    FOREIGN KEY (trip_request_id) REFERENCES trip_request(id),
    FOREIGN KEY (transport_id) REFERENCES transport(number_plate),
    FOREIGN KEY (driver_id) REFERENCES driver(id)
);


